//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.10.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "servicesControls"
	/// <summary>Services Controls</summary>
	public partial interface IServicesControls : IPublishedContent
	{
		/// <summary>Services List</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.ServiceItem> ServicesList { get; }

		/// <summary>Services Subtitle</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		string ServicesSubtitle { get; }

		/// <summary>Services Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		string ServicesTitle { get; }
	}

	/// <summary>Services Controls</summary>
	[PublishedModel("servicesControls")]
	public partial class ServicesControls : PublishedContentModel, IServicesControls
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const string ModelTypeAlias = "servicesControls";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ServicesControls, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ServicesControls(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Services List: Choose service items to add to the list
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("servicesList")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.ServiceItem> ServicesList => GetServicesList(this);

		/// <summary>Static getter for Services List</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.ServiceItem> GetServicesList(IServicesControls that) => that.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.ServiceItem>>("servicesList");

		///<summary>
		/// Services Subtitle: Enter the subtitle of the services section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("servicesSubtitle")]
		public string ServicesSubtitle => GetServicesSubtitle(this);

		/// <summary>Static getter for Services Subtitle</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static string GetServicesSubtitle(IServicesControls that) => that.Value<string>("servicesSubtitle");

		///<summary>
		/// Services Title: Enter the title of the services section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("servicesTitle")]
		public string ServicesTitle => GetServicesTitle(this);

		/// <summary>Static getter for Services Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static string GetServicesTitle(IServicesControls that) => that.Value<string>("servicesTitle");
	}
}
