//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.10.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Targeted Item</summary>
	[PublishedModel("targetedItem")]
	public partial class TargetedItem : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const string ModelTypeAlias = "targetedItem";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TargetedItem, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public TargetedItem(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Targeted Item Description: Enter a short description of this targeted item
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("targetedItemDescription")]
		public string TargetedItemDescription => this.Value<string>("targetedItemDescription");

		///<summary>
		/// Targeted Item Image: Choose the image to display for this targeted item
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("targetedItemImage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent TargetedItemImage => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("targetedItemImage");

		///<summary>
		/// Targeted Item Name: Enter the name of this targeted item
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("targetedItemName")]
		public string TargetedItemName => this.Value<string>("targetedItemName");

		///<summary>
		/// Targeted Item Page: Choose the page to link to for this targeted item
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.1")]
		[ImplementPropertyType("targetedItemPage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent TargetedItemPage => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("targetedItemPage");
	}
}
