//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appintern.Web.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class chartCountMembers
    {
        public long RowID { get; set; }
        public string MemberType { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<decimal> Percentage { get; set; }
    }
}
