//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appintern.Web.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employers
    {
        public int MemberID { get; set; }
        public string TaxNumber { get; set; }
        public string CompanyName { get; set; }
        public string ContactPerson { get; set; }
        public string Headquarters { get; set; }
        public string Country { get; set; }
        public string JobSector1 { get; set; }
        public string JobSector2 { get; set; }
        public string JobSector3 { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string SocialMedia { get; set; }
        public string LoginName { get; set; }
    }
}
