//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appintern.Web.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiaisonOfficers
    {
        public int MemberID { get; set; }
        public string TaxNumber { get; set; }
        public string FullName { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string OfficeAddress { get; set; }
        public string Occupation { get; set; }
        public string Employer { get; set; }
        public string LoginName { get; set; }
    }
}
